
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /img
  static_dir: static/img

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /fonts
  static_dir: static/fonts

- url: /.*
  script: blog.app

- url: /templates
  static_dir: templates
  application_readable: true

libraries:
- name: jinja2
  version: latest

- name: PIL
  version: "1.1.7"